plugins {
    id 'java'
    id 'application'
}

group 'net.monclient'
version '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // Utilisation des versions directes hébergées sur Maven Central
    implementation 'fr.litarvan:openauth:1.1.8'
    implementation 'net.thetechisalive:openlauncherlib:3.2.3'
}

application {
    mainClass = 'net.monclient.launcher.Main'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': 'net.monclient.launcher.Main'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
